target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'HealthKMP', :path => '../core'
  pod 'HealthKMPKoin', :path => '../koin'
  pod 'HealthKMPSample', :path => '../sample'
  pod 'FirebaseCore', '~> 11.2.0'
  pod 'FirebaseAuth', '~> 11.2.0'
end
